<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseDistribuidor extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('distribuidor');
        $this->hasColumn('id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'autoincrement' => true, 'length' => '4'));
        $this->hasColumn('nombre', 'string', 255, array('type' => 'string', 'length' => '255'));
    }

    public function setUp()
    {
        $this->hasMany('Encuesta as Encuestas', array('local' => 'id',
                                                      'foreign' => 'last_dist_id'));
    }
}