<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseEncuesta extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('encuesta');
        $this->hasColumn('id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'autoincrement' => true, 'length' => '4'));
        $this->hasColumn('encuestador_id', 'integer', 4, array('type' => 'integer', 'length' => '4'));
        $this->hasColumn('viewer_id', 'integer', 4, array('type' => 'integer', 'length' => '4'));
        $this->hasColumn('last_dist_id', 'integer', 4, array('type' => 'integer', 'length' => '4'));
        $this->hasColumn('nombre', 'string', 255, array('type' => 'string', 'notnull' => true, 'length' => '255'));
        $this->hasColumn('apellido_p', 'string', 255, array('type' => 'string', 'notnull' => true, 'length' => '255'));
        $this->hasColumn('apellido_m', 'string', 255, array('type' => 'string', 'notnull' => true, 'length' => '255'));
        $this->hasColumn('rfc', 'string', 50, array('type' => 'string', 'length' => '50'));
        $this->hasColumn('edad', 'integer', 4, array('type' => 'integer', 'notnull' => true, 'length' => '4'));
        $this->hasColumn('genero', 'string', 1, array('type' => 'string', 'notnull' => true, 'length' => '1'));
        $this->hasColumn('telefono', 'string', 50, array('type' => 'string', 'notnull' => true, 'length' => '50'));
        $this->hasColumn('celular', 'string', 50, array('type' => 'string', 'length' => '50'));
        $this->hasColumn('email', 'string', 255, array('type' => 'string', 'length' => '255'));
        $this->hasColumn('estado_id', 'integer', 4, array('type' => 'integer', 'notnull' => true, 'length' => '4'));
        $this->hasColumn('ciudad', 'string', 50, array('type' => 'string', 'notnull' => true, 'length' => '50'));
        $this->hasColumn('municipio', 'string', 50, array('type' => 'string', 'notnull' => true, 'length' => '50'));
        $this->hasColumn('colonia', 'string', 50, array('type' => 'string', 'notnull' => true, 'length' => '50'));
        $this->hasColumn('calle', 'string', 50, array('type' => 'string', 'notnull' => true, 'length' => '50'));
        $this->hasColumn('numero', 'string', 50, array('type' => 'string', 'notnull' => true, 'length' => '50'));
        $this->hasColumn('cp', 'integer', 4, array('type' => 'integer', 'notnull' => true, 'length' => '4'));
    }

    public function setUp()
    {
        $this->hasOne('sfGuardUser as Encuestador', array('local' => 'encuestador_id',
                                                          'foreign' => 'id'));

        $this->hasOne('sfGuardUser as Viewer', array('local' => 'viewer_id',
                                                     'foreign' => 'id'));

        $this->hasOne('Distribuidor as LastDist', array('local' => 'last_dist_id',
                                                        'foreign' => 'id'));

        $this->hasOne('Estado', array('local' => 'estado_id',
                                      'foreign' => 'id'));

        $this->hasMany('Horario as Horarios', array('refClass' => 'EncuestaHorario',
                                                    'local' => 'encuesta_id',
                                                    'foreign' => 'horario_id'));

        $this->hasMany('AreaInteres as AreasInteres', array('refClass' => 'EncuestaAreaInteres',
                                                            'local' => 'encuesta_id',
                                                            'foreign' => 'area_interes_id'));

        $this->hasMany('ProductoInteres as ProductosInteres', array('refClass' => 'EncuestaProductoInteres',
                                                                    'local' => 'encuesta_id',
                                                                    'foreign' => 'producto_interes_id'));

        $this->hasMany('MedioContacto as MediosContacto', array('refClass' => 'EncuestaMedioContacto',
                                                                'local' => 'encuesta_id',
                                                                'foreign' => 'medio_contacto_id'));

        $this->hasMany('EncuestaHorario', array('local' => 'id',
                                                'foreign' => 'encuesta_id'));

        $this->hasMany('EncuestaAreaInteres', array('local' => 'id',
                                                    'foreign' => 'encuesta_id'));

        $this->hasMany('EncuestaProductoInteres', array('local' => 'id',
                                                        'foreign' => 'encuesta_id'));

        $this->hasMany('EncuestaMedioContacto', array('local' => 'id',
                                                      'foreign' => 'encuesta_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}