<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseProductoInteres extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('producto_interes');
        $this->hasColumn('id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'autoincrement' => true, 'length' => '4'));
        $this->hasColumn('descripcion', 'string', 255, array('type' => 'string', 'length' => '255'));
    }

    public function setUp()
    {
        $this->hasMany('EncuestaProductoInteres', array('local' => 'id',
                                                        'foreign' => 'producto_interes_id'));
    }
}