<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseEncuesta extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('encuesta');
        $this->hasColumn('id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'autoincrement' => true, 'length' => '4'));
        $this->hasColumn('encuestador_id', 'integer', 4, array('type' => 'integer', 'length' => '4'));
        $this->hasColumn('nombre', 'string', 255, array('type' => 'string', 'notnull' => true, 'length' => '255'));
        $this->hasColumn('apellido_p', 'string', 255, array('type' => 'string', 'length' => '255'));
        $this->hasColumn('apellido_m', 'string', 255, array('type' => 'string', 'length' => '255'));
        $this->hasColumn('rfc', 'string', 50, array('type' => 'string', 'length' => '50'));
        $this->hasColumn('edad', 'integer', 4, array('type' => 'integer', 'length' => '4'));
        $this->hasColumn('genero', 'string', 1, array('type' => 'string', 'length' => '1'));
        $this->hasColumn('telefono', 'string', 50, array('type' => 'string', 'length' => '50'));
        $this->hasColumn('celular', 'string', 50, array('type' => 'string', 'length' => '50'));
        $this->hasColumn('email', 'string', 255, array('type' => 'string', 'length' => '255'));
        $this->hasColumn('estado_id', 'integer', 4, array('type' => 'integer', 'length' => '4'));
        $this->hasColumn('ciudad', 'string', 50, array('type' => 'string', 'length' => '50'));
        $this->hasColumn('delegacion', 'string', 50, array('type' => 'string', 'length' => '50'));
        $this->hasColumn('municipio', 'string', 50, array('type' => 'string', 'length' => '50'));
        $this->hasColumn('colonia', 'string', 50, array('type' => 'string', 'length' => '50'));
        $this->hasColumn('calle', 'string', 50, array('type' => 'string', 'length' => '50'));
        $this->hasColumn('numero', 'integer', 10, array('type' => 'integer', 'length' => '10'));
        $this->hasColumn('cp', 'integer', 10, array('type' => 'integer', 'length' => '10'));
    }

    public function setUp()
    {
        $this->hasOne('sfGuardUser as Encuestador', array('local' => 'encuestador_id',
                                                          'foreign' => 'id'));

        $this->hasOne('Estado', array('local' => 'estado_id',
                                      'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}