<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseCiudad extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ciudad');
        $this->hasColumn('id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'autoincrement' => true, 'length' => '4'));
        $this->hasColumn('estado_id', 'integer', 4, array('type' => 'integer', 'length' => '4'));
        $this->hasColumn('nombre', 'string', 255, array('type' => 'string', 'notnull' => true, 'length' => '255'));
    }

    public function setUp()
    {
        $this->hasOne('Estado', array('local' => 'estado_id',
                                      'foreign' => 'id'));
    }
}