<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Ciudad extends BaseCiudad
{
  public function __toString()
  {
    return isset($this->nombre) ? $this->nombre : '';
  }
}
