<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EncuestaTable extends Doctrine_Table
{
  public function getLeadsQuery(Doctrine_Query $q)
  {
    $alias = $q->getRootAlias();

    return $q
      ->leftJoin("$alias.Estado edo")
      ->leftJoin("$alias.Encuestador e")
      ->addWhere("$alias.last_dist_id IS NULL")
      ->addOrderBy("$alias.created_at")
    ;
  }

  public function getListQuery(Doctrine_Query $q)
  {
    $alias = $q->getRootAlias();

    return $q
      ->leftJoin("$alias.Estado edo")
      ->leftJoin("$alias.Encuestador e")
      ->addOrderBy("$alias.nombre")
      ->addOrderBy("$alias.apellido_p")
    ;
  }

  /**
   * Debe regresar seguimiento_count
   */
  public function getForSeguimiento($params)
  {
    $encuesta = $this->createQuery('e')
      ->select('e.nombre, e.ciudad, edo.nombre, e.viewer_id')
      ->addSelect('SUM(s.localizo_dist) AS seguimiento_count')
      ->leftJoin('e.Estado edo')
      ->leftJoin('e.Seguimiento s')
      ->addWhere('e.id = ?', $params['id'])
      ->fetchOne();
    $encuesta->Seguimiento = new Doctrine_Collection('Seguimiento');

    return $encuesta;
  }

  public function getForShow($params)
  {
    return $this->createQuery('e')
      ->leftJoin('e.Encuestador')
      ->leftJoin('e.Estado')
      ->leftJoin('e.LastDist')
      ->leftJoin('e.Horarios')
      ->leftJoin('e.AreasInteres')
      ->leftJoin('e.ProductosInteres')
      ->leftJoin('e.MediosContacto')
      ->addWhere('e.id = ?', $params['id'])
      ->fetchOne();
  }

  public function unlockAll($agent_id)
  {
    return Doctrine_Query::create()
      ->update('Encuesta e')
      ->set('e.viewer_id', 'NULL')
      ->addWhere('e.viewer_id = ?', $agent_id)
      ->execute();
  }
}
