<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductoInteres extends BaseProductoInteres
{
  public function __toString()
  {
    return $this->descripcion;
  }
}
