<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SeguimientoTable extends Doctrine_Table
{
  public function findForLead($lead_id)
  {
    return $this->createQuery('s')
      ->select('s.*, a.username, d.*')
      ->leftJoin('s.Agente a')
      ->leftJoin('s.Distribuidor d')
      ->addWhere('s.lead_id = ?', $lead_id)
      ->orderBy('s.created_at')
      ->execute();
  }

  public function findVuelta1()
  {
    return $this->findVueltaQuery()
      ->addWhere('s.intento = 1')
      ->addWhere('s.fecha_localizo_dist < (NOW() - interval 30 second)') // 2 day
      ->execute(array(), Doctrine::HYDRATE_ARRAY);
  }

  public function findVuelta2()
  {
    return $this->findVueltaQuery()
      ->addWhere('s.intento >= 2')
      ->addWhere('s.fecha_localizo_dist < (NOW() - interval 30 second)') // 1 day
      ->execute(array(), Doctrine::HYDRATE_ARRAY);
  }

  public function findVueltaQuery()
  {
    return Doctrine::getTable('Encuesta')->createQuery('l')
      ->select('l.id, l.nombre, l.apellido_p, l.apellido_m, edo.nombre, l.ciudad')
      ->addSelect('s.fecha_localizo_dist, d.name, h.rango')
      ->leftJoin('l.Seguimiento s')
      ->leftJoin('l.Estado edo')
      ->leftJoin('l.Horarios h')
      ->leftJoin('s.Distribuidor d')
      ->addWhere('l.viewer_id IS NULL')
      ->addWhere('s.status = 1')
      ->addOrderBy('s.fecha_localizo_dist ASC')
      ->limit(100);
  }

  public function closeForLead($lead_id)
  {
    return $this->createQuery('s')
      ->update()
      ->set('s.status', 0)
      ->where('s.lead_id = ?', $lead_id)
      ->execute();
  }

  public function getTabTriesPerAgents($from, $to, $vuelta = 1)
  {
    $dbh = $this->getConnection();
    $stmt = $dbh->prepare("SELECT COUNT(s.id) count, a.username
      FROM sf_guard_user a LEFT JOIN seguimiento s ON s.agente_id = a.id
      WHERE s.created_at BETWEEN ? AND ? + interval 1 day AND intento = ?
      GROUP BY s.agente_id
    ");
    $stmt->execute(array($from, $to, $vuelta));

    return axaiToolkit::toKeyValueArray('username', 'count', $stmt->fetchAll());
  }

  public function getTabPerAgents($from, $to, $vuelta = 1)
  {
    $dbh = $this->getConnection();
    $stmt = $dbh->prepare("SELECT COUNT(s.id) count, a.username
      FROM sf_guard_user a LEFT JOIN seguimiento s ON s.agent_localizo_dist = a.id
      WHERE s.fecha_localizo_dist BETWEEN ? AND ? + interval 1 day AND intento = ?
        AND s.localizo_dist = 1
      GROUP BY s.agent_localizo_dist
    ");
    $stmt->execute(array($from, $to, $vuelta));

    return axaiToolkit::toKeyValueArray('username', 'count', $stmt->fetchAll());
  }

  public function getLeadPerAgents($from, $to, $vuelta = 1)
  {
    $dbh = $this->getConnection();
    $stmt = $dbh->prepare("SELECT COUNT(s.id) count, a.username
      FROM sf_guard_user a LEFT JOIN seguimiento s ON s.agent_localizo_lead = a.id
      WHERE s.fecha_localizo_lead BETWEEN ? AND ? + interval 1 day AND intento = ?
      GROUP BY s.agent_localizo_lead
    ");
    $stmt->execute(array($from, $to, $vuelta));

    return axaiToolkit::toKeyValueArray('username', 'count', $stmt->fetchAll());
  }

  public function getLeadPerTab($from, $to, $vuelta = 1)
  {
    $dbh = $this->getConnection();
    $stmt = $dbh->prepare("SELECT COUNT(s.id) count, d.id
      FROM distribuidor d LEFT JOIN seguimiento s ON s.distribuidor_id = d.id
      WHERE s.created_at BETWEEN ? AND ? + interval 1 day AND intento = ?
      GROUP BY s.distribuidor_id
    ");
    $stmt->execute(array($from, $to, $vuelta));

    return axaiToolkit::toKeyValueArray('id', 'count', $stmt->fetchAll());
  }

  public function getSegPerTab($from, $to, $vuelta = 1)
  {
    $dbh = $this->getConnection();
    $stmt = $dbh->prepare("SELECT COUNT(s.id) count, d.id
      FROM distribuidor d LEFT JOIN seguimiento s ON s.distribuidor_id = d.id
      WHERE s.created_at BETWEEN ? AND ? + interval 1 day AND intento = ?
        AND localizo_lead = 1
      GROUP BY s.distribuidor_id
    ");
    $stmt->execute(array($from, $to, $vuelta));

    return axaiToolkit::toKeyValueArray('id', 'count', $stmt->fetchAll());
  }
}
