<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Seguimiento extends BaseSeguimiento
{
  public function preSave($event)
  {
    $modified = $this->getModified();

    if (array_key_exists('localizo_dist', $modified) && php_sapi_name() != 'cli')
    {
      if ($this->localizo_dist) {
        Doctrine::getTable('Encuesta')->setLastDist($this->lead_id, $this->distribuidor_id);
      } else {
        Doctrine::getTable('Encuesta')->unsetLastDist($this->lead_id);
        $this->localizo_lead = null;
      }
      $this->fecha_localizo_dist = new Doctrine_Expression('NOW()');
    }

    if (array_key_exists('localizo_lead', $modified))
    {
      if ($this->localizo_lead === false && $this->intento == 1) {
        Doctrine::getTable('Encuesta')->unsetLastDist($this->lead_id);
      }
      $this->fecha_localizo_lead = new Doctrine_Expression('NOW()');
    }

    if (!array_key_exists('status', $modified))
    {
      if ($this->localizo_dist && !$this->localizo_lead) {
        $this->status = 1;
      } else {
        $this->status = 0;
      }
    }
  }

  public function pasoTiempoVuelta()
  {
    if ($this->intento == 1)
    {
      $tiempo_espera = sfConfig::get('app_tiempo_espera_vuelta_1');
    }
    else if ($this->intento > 1)
    {
      $tiempo_espera = sfConfig::get('app_tiempo_espera_vuelta_2');
    }
    else return false;

    return strtotime($this->fecha_localizo_dist . "+$tiempo_espera") < time();
  }
}
