<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUser extends PluginsfGuardUser
{
  public function __toString()
  {
    return $this->username ? $this->username : '';
  }
}
