encuesta:
  class: sfDoctrineRouteCollection
  options:
    model:      Encuesta
    with_show:  true
    collection_actions: { filter: post }

leads:
  class: sfDoctrineRouteCollection
  options:
    model:      Encuesta
    collection_actions: { filter: post }

distribuidor:
  class: sfDoctrineRouteCollection
  options:
    model: Distribuidor
    collection_actions: { filter: post }

seguimiento_create:
  url: /seguimiento/:id/create
  class: sfDoctrineRoute
  options: { model: Encuesta, type: object, method: getForSeguimiento }
  param: { module: seguimiento, action: create }

# default rules
homepage:
  url:   /
  param: { module: encuesta, action: index }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
