encuesta:
  class: sfDoctrineRouteCollection
  options:
    model:      Encuesta
    collection_actions: { filter: post }
    object_actions: { editId: get, updateId: post }
    model_methods: { object: getForShow }

leads:
  class: sfDoctrineRouteCollection
  options:
    model:      Encuesta
    collection_actions: { filter: post }

distribuidor:
  class: sfDoctrineRouteCollection
  options:
    model: Distribuidor
    collection_actions: { filter: post }
    model_methods: { object: getForShow }

seguimiento_createForLead:
  url: /seguimiento/:id/create
  class: sfDoctrineRoute
  options: { model: Encuesta, type: object, method: getForSeguimiento }
  param: { module: seguimiento, action: create }

seguimiento:
  class: sfDoctrineRouteCollection
  options:
    model: Seguimiento
    object_actions: { finalizar: get, localizoDist: get, localizoLead: get }

ciudad_ajaxList:
  url:   /ciudad/ajaxList
  param: { module: ciudad, action: ajaxList }

# default rules
homepage:
  url:   /
  param: { module: encuesta, action: new }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
