encuesta:
  class: sfDoctrineRouteCollection
  options:
    model:      Encuesta
    with_show:  true
    collection_actions: { filter: post }

# default rules
homepage:
  url:   /
  param: { module: default, action: index }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
