encuesta:
  class: sfDoctrineRouteCollection
  options:
    model:      Encuesta
    with_show:  true
    collection_actions: { filter: post }
    model_methods: { object: getForShow }

leads:
  class: sfDoctrineRouteCollection
  options:
    model:      Encuesta
    collection_actions: { filter: post }

distribuidor:
  class: sfDoctrineRouteCollection
  options:
    model: Distribuidor
    collection_actions: { filter: post }

seguimiento:
  url: /seguimiento
  param: { module: seguimiento, action: index }

seguimiento_create:
  url: /seguimiento/:id/create
  class: sfDoctrineRoute
  options: { model: Encuesta, type: object, method: getForSeguimiento }
  param: { module: seguimiento, action: create }

seguimiento_finalizar:
  url: /seguimiento/:id/finalizar
  class: sfDoctrineRoute
  options: { model: Seguimiento, type: object }
  param: { module: seguimiento, action: finalizar }

seguimiento_localizoDist:
  url: /seguimiento/:id/localizoDist
  class: sfDoctrineRoute
  options: { model: Seguimiento, type: object }
  param: { module: seguimiento, action: localizoDist }

seguimiento_localizoLead:
  url: /seguimiento/:id/localizoLead
  class: sfDoctrineRoute
  options: { model: Seguimiento, type: object }
  param: { module: seguimiento, action: localizoLead }

# default rules
homepage:
  url:   /
  param: { module: encuesta, action: index }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
