all:
  encuesta1:
    class:        sfDoctrineDatabase
    param:
      dsn:        mysql:dbname=tvpresence;host=localhost
      username:   tvpresence_usr
      password:   tvpresence_pwd
      encoding:   utf8
