newSuccess:
  http_metas:
    Pragma: no-cache
    Cache-Control: no-cache

showSuccess:
  http_metas:
    Pragma: no-cache
    Cache-Control: no-cache

indexSuccess:
  stylesheets: [start/jquery-ui.custom.css]
  javascripts: [jquery-ui.js, ui.datepicker-es.js]
