Encuesta:
  actAs: [Timestampable]
  columns:
    id:
      type:         integer(4)
      primary:      true
      autoincrement: true
    encuestador_id: integer(4)

    # datos
    nombre:         { type: string(255), notnull: true }
    apellido_p:     { type: string(255), notnull: true }
    apellido_m:     { type: string(255), notnull: true }
    rfc:            string(50)
    edad:           { type: integer(4), notnull: true }
    genero:         { type: string(1), notnull: true }
    telefono:       { type: string(50), notnull: true }
    celular:        string(50)
    email:          string(255)

    # direccion
    estado_id:      { type: integer(4), notnull: true }
    ciudad:         { type: string(50), notnull: true }
    municipio:      { type: string(50), notnull: true }
    colonia:        { type: string(50), notnull: true }
    calle:          { type: string(50), notnull: true }
    numero:         { type: string(50), notnull: true }
    cp:             { type: integer(4), notnull: true }
  relations:
    Encuestador:
      class:        sfGuardUser
      local:        encuestador_id
      foreign:      id
      foreignAlias: Encuestas
    Estado:
      foreignAlias: Encuestas

    Horarios:
      class: Horario
      refClass: EncuestaHorario
      foreignAlias: Encuestas
    AreasInteres:
      class: AreaInteres
      refClass: EncuestaAreaInteres
      foreignAlias: Encuestas
    ProductosInteres:
      class: ProductoInteres
      refClass: EncuestaProductoInteres
      foreignAlias: Encuestas
    MediosContacto:
      class: MedioContacto
      refClass: EncuestaMedioContacto
      foreignAlias: Encuestas

Estado:
  columns:
    id:
      type:         integer(4)
      primary:      true
      autoincrement: true
    nombre:
      type:         string(255)
      notnull:      true

Horario:
  columns:
    id:
      type:         integer(4)
      primary:      true
      autoincrement: true
    descripcion:    string(255)

EncuestaHorario:
  columns:
    encuesta_id: { type: integer(4), primary: true }
    horario_id: { type: integer(4), primary: true }
  relations:
    Encuesta:
      local: encuesta_id
      onDelete: CASCADE
    Horario:
      local: horario_id
      onDelete: CASCADE

AreaInteres:
  columns:
    id:
      type:         integer(4)
      primary:      true
      autoincrement: true
    descripcion:    string(255)

EncuestaAreaInteres:
  columns:
    encuesta_id: { type: integer(4), primary: true }
    area_interes_id: { type: integer(4), primary: true }
  relations:
    Encuesta:
      local: encuesta_id
      onDelete: CASCADE
    AreaInteres:
      local: area_interes_id
      onDelete: CASCADE

ProductoInteres:
  columns:
    id:
      type:         integer(4)
      primary:      true
      autoincrement: true
    descripcion:    string(255)

EncuestaProductoInteres:
  columns:
    encuesta_id: { type: integer(4), primary: true }
    producto_interes_id: { type: integer(4), primary: true }
  relations:
    Encuesta:
      local: encuesta_id
      onDelete: CASCADE
    ProductoInteres:
      local: producto_interes_id
      onDelete: CASCADE

MedioContacto:
  columns:
    id:
      type:         integer(4)
      primary:      true
      autoincrement: true
    descripcion:    string(255)

EncuestaMedioContacto:
  columns:
    encuesta_id: { type: integer(4), primary: true }
    medio_contacto_id: { type: integer(4), primary: true }
  relations:
    Encuesta:
      local: encuesta_id
      onDelete: CASCADE
    MedioContacto:
      local: medio_contacto_id
      onDelete: CASCADE

